<html>
    <title>Проект на html</title>
    <body>
        <header>Шапка</header>
        <main>
            <h1>Games Lab</h1>
            <h2>Студия разработки игр</h2>
            <h2 id="games">Мы работаем в разных жанрах</h2>
            <p>Хотите сделать игру по вашему сценарию? 
                <br>У вас уже есть игра, которую нужно доработать для мобильных устройств или для продажи в другую страну?
                <br>У нас можно заказать разработку или доработку игры. 
                <br>Мы работаем в самых разных жанрах: шутеры, квесты, игры на логику и скорость.
                <br>Также создаём игры смешанных жанров, игры развивающие полезные навыки: внимание, память, мышление.
            </p>

            <h2>Процесс работы</h2>
            <p>Создание игры — это всегда командная работа из нескольких этапов: 
                <br>планирование сюжета, создание графических объектов, программирование, несколько этапов тестирования.
                <br>Над игрой работают программист, дизайнер, сценарист, звукорежиссёр, редактор, переводчик и многие другие специалисты.
            </p>
            <h2 id="price">Наше предложение</h2>
            <table style="border-collapse:collapse;border:1px solid green;">
                <tr style="border:1px solid green;background-color:palegreen;">
                    <td>Вид работы</td>
                    <td>Подробности</td>
                    <td>Цена</td>
                </tr>
                <tr style="border:1px solid green;">
                    <td style="background-color:palegreen;">Портирование</td>
                    <td>Destop, Android, iOS</td>
                    <td>от 50 тыс. руб.</tr>
                </tr>
                <tr style="border:1px solid green;">
                    <td style="background-color:palegreen;">Локализация</td>
                    <td>Перевод: тексты, <br>голоса, графика</td>
                    <td>от 50 тыс. руб.</td>
                </tr>
            <tr style="border:1px solid green;">
                <td style="background-color:palegreen;">Создание <br>контента</td>
                <td>Звук, музыка, <br>графика 3D, 2D</td>
                <td>от 50 руб./час</td>
            </tr>
            <tr style="border:1px solid green;">
                <td style="background-color:palegreen;">Игра под ключ</td>
                <td>Обсуждение сюжета <br>со сценаристом</td>
                <td>Договорная</td>
            </tr>
            </table>
            <h2>Популярность продукта</h2>
            <p>Наши игры можно увидеть на городских соревнованиях по киберспорту:</p>
        </main>
        <footer>Подвал</footer>
    </body>
</html>
